[theme]
primaryColor = "#fa9f3d"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = true
fileWatcherType = "none"   # opcional: desactiva watcher (menos redeploys autom√°ticos)

[logger]
level = "info"